[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "morag-video"
version = "0.1.0"
description = "Video processing service for MoRAG (Modular Retrieval Augmented Generation)"
authors = [
    {name = "MoRAG Team"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "morag-core>=0.1.0",
    "morag-embedding>=0.1.0",
    "morag-audio>=0.1.0",
    "opencv-python>=4.5.0",
    "ffmpeg-python>=0.2.0",
    "numpy>=1.20.0",
    "pillow>=9.0.0",
    "scikit-image>=0.19.0",
    "structlog>=23.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "black>=23.0.0",
    "isort>=5.0.0",
    "flake8>=6.0.0",
    "mypy>=1.0.0",
]
scene = [
    "scenedetect>=0.6.0",
    "torch>=1.10.0",
]
ocr = [
    "pytesseract>=0.3.9",
    "easyocr>=1.6.0",
]

[project.urls]
Homepage = "https://github.com/yourusername/morag"
Documentation = "https://github.com/yourusername/morag#readme"
Repository = "https://github.com/yourusername/morag.git"
Issues = "https://github.com/yourusername/morag/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 100
target-version = ['py38']

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true