services:
  # Infrastructure Services
  redis:
    image: redis:7-alpine
    container_name: morag-redis-micro
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes

  qdrant:
    image: qdrant/qdrant:latest
    container_name: morag-qdrant-micro
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334

  # Core MoRAG Services
  morag-api:
    build:
      context: .
      target: production
    container_name: morag-api-micro
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
    depends_on:
      - redis
      - qdrant
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp

  # Celery Workers for processing
  morag-worker-1:
    build:
      context: .
      target: production
    container_name: morag-worker-1-micro
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./uploads:/app/uploads
    command: ["celery", "-A", "morag_worker", "worker", "--loglevel=info", "--concurrency=2"]

  morag-worker-2:
    build:
      context: .
      target: production
    container_name: morag-worker-2-micro
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    command: ["celery", "-A", "morag_worker", "worker", "--loglevel=info", "--concurrency=2"]

volumes:
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  default:
    name: morag-microservices
    driver: bridge
