services:
  # Redis for development
  redis:
    image: redis:7-alpine
    container_name: morag-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_dev_data:/data
    command: redis-server --appendonly yes

#  # Qdrant vector database for development
#  qdrant:
#    image: qdrant/qdrant:latest
#    container_name: morag-qdrant-dev
#    restart: unless-stopped
#    ports:
#      - "6333:6333"
#      - "6334:6334"
#    volumes:
#      - qdrant_dev_data:/qdrant/storage
#    environment:
#      - QDRANT__SERVICE__HTTP_PORT=6333
#      - QDRANT__SERVICE__GRPC_PORT=6334

  # MoRAG API Server for development
  morag-api-dev:
    build:
      context: .
      target: development
    container_name: morag-api-dev
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./uploads:/app/uploads
    env_file: .env
    depends_on:
      - redis
#      - qdrant
    command: ["uvicorn", "morag.server:create_app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--factory"]

  # Development worker
  morag-worker-dev:
    build:
      context: .
      target: development
    container_name: morag-worker-dev
    restart: unless-stopped
    volumes:
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
      - ./uploads:/app/uploads
    env_file: .env
    depends_on:
      - redis
    command: ["celery", "-A", "morag.worker", "worker", "--loglevel=debug", "--concurrency=1"]

volumes:
  redis_dev_data:
    driver: local
  qdrant_dev_data:
    driver: local

networks:
  default:
    name: morag-dev-network
    driver: bridge
