services:
  # Redis for task queue
  redis:
    image: redis:7.2-alpine
    container_name: morag-redis-prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --maxmemory 512mb --maxmemory-policy allkeys-lru
    networks:
      - morag-network

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: morag-qdrant-prod
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - morag-network

  # Main API service
  morag-api:
    build:
      context: .
      target: production
    container_name: morag-api-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    depends_on:
      - redis
      - qdrant
    networks:
      - morag-network

  # Celery workers
  morag-worker-1:
    build:
      context: .
      target: production
    container_name: morag-worker-1-prod
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./temp:/app/temp
      - ./logs:/app/logs
    depends_on:
      - redis
    command: ["celery", "-A", "morag.worker", "worker", "--loglevel=info", "--concurrency=2"]
    networks:
      - morag-network

  morag-worker-2:
    build:
      context: .
      target: production
    container_name: morag-worker-2-prod
    restart: unless-stopped
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_URL=http://qdrant:6333
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./temp:/app/temp
      - ./logs:/app/logs
    depends_on:
      - redis
    command: ["celery", "-A", "morag.worker", "worker", "--loglevel=info", "--concurrency=2"]
    networks:
      - morag-network

volumes:
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  morag-network:
    driver: bridge
