services:

  # Qdrant vector database
  qdrant:
    image: qdrant/qdrant:v1.7.4
    container_name: morag-qdrant-prod
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    networks:
      - morag-network

  # Main API service
  morag-api:
    build:
      context: .
      target: production
    container_name: morag-api-prod
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    depends_on:
      - qdrant
    networks:
      - morag-network

  # Note: Production workers have been replaced with HTTP-based remote workers
  # Use docker-compose.workers.yml for remote worker deployment
  # Or run: python scripts/start_http_remote_worker.py --server-url http://your-server:8000 --api-key your-key

volumes:
  qdrant_data:
    driver: local

networks:
  morag-network:
    driver: bridge
