services:
  # Redis for task queue and caching
  redis:
    image: redis:7-alpine
    container_name: morag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    # Note: To fix memory overcommit warning, run on host:
    # echo 'vm.overcommit_memory = 1' | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

  # Qdrant vector database
#  qdrant:
#    image: qdrant/qdrant:latest
#    container_name: morag-qdrant
#    restart: unless-stopped
#    ports:
#      - "6333:6333"
#      - "6334:6334"
#    volumes:
#      - qdrant_data:/qdrant/storage
#    environment:
#      - QDRANT__SERVICE__HTTP_PORT=6333
#      - QDRANT__SERVICE__GRPC_PORT=6334

  # MoRAG API Server
  morag-api:
    build:
      context: .
      target: production
    container_name: morag-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp


  # Celery Worker for background tasks
  morag-worker-1:
    build:
      context: .
      target: production
    container_name: morag-worker-1
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    command: ["celery", "-A", "morag.worker", "worker", "--loglevel=info", "--concurrency=2"]

  morag-worker-2:
    build:
      context: .
      target: production
    container_name: morag-worker-2
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    command: ["celery", "-A", "morag.worker", "worker", "--loglevel=info", "--concurrency=2"]

  # Celery Beat for scheduled tasks
  morag-beat:
    build:
      context: .
      target: production
    container_name: morag-beat
    restart: unless-stopped
    env_file: .env
    depends_on:
      - redis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["celery", "-A", "morag.worker", "beat", "--loglevel=info"]

volumes:
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  default:
    name: morag-network
    driver: bridge
