services:
  # Redis for task queue and caching
  redis:
    image: redis:7-alpine
    container_name: morag-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    # Note: To fix memory overcommit warning, run on host:
    # echo 'vm.overcommit_memory = 1' | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: peak4tw
      MARIADB_USER: morag
      MARIADB_PASSWORD: morag1234
      MARIADB_DATABASE: morag
    volumes:
      - /var/docker/mariadb:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 81:80
    environment:
      - PMA_HOST=mariadb
      - PMA_ABSOLUTE_URI=https://db.morag.drydev.de
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morag-phpmyadmin.entrypoints=websecure"
      - "traefik.http.routers.morag-phpmyadmin.rule=Host(`db.morag.drydev.de`)"
      - "traefik.http.routers.morag-phpmyadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.morag-phpmyadmin.loadbalancer.server.port=81"

  # Qdrant vector database
#  qdrant:
#    image: qdrant/qdrant:latest
#    container_name: morag-qdrant
#    restart: unless-stopped
#    ports:
#      - "6333:6333"
#      - "6334:6334"
#    volumes:
#      - qdrant_data:/qdrant/storage
#    environment:
#      - QDRANT__SERVICE__HTTP_PORT=6333
#      - QDRANT__SERVICE__GRPC_PORT=6334

  # MoRAG API Server
  morag-api:
    build:
      context: .
      target: production
    container_name: morag-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: .env
    environment:
      - HF_HOME=/app/temp/cache/huggingface
      - TRANSFORMERS_CACHE=/app/temp/cache/huggingface
      - WHISPER_CACHE_DIR=/app/temp/cache/whisper
      # CPU Compatibility Settings
      - MORAG_FORCE_CPU=true
      - MORAG_DISABLE_DOCLING=false
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      # PyTorch CPU Compatibility
      - PYTORCH_DISABLE_NNPACK=1
      - PYTORCH_DISABLE_AVX=1
      - PYTORCH_DISABLE_AVX2=1
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp


  # Celery Worker for background tasks
  morag-worker-1:
    build:
      context: .
      target: production
    container_name: morag-worker-1
    restart: unless-stopped
    env_file: .env
    environment:
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
      # CPU Compatibility Settings
      - MORAG_FORCE_CPU=true
      - MORAG_DISABLE_DOCLING=false
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      # PyTorch CPU Compatibility
      - PYTORCH_DISABLE_NNPACK=1
      - PYTORCH_DISABLE_AVX=1
      - PYTORCH_DISABLE_AVX2=1
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    command: ["scripts/start_worker_safe.sh", "celery", "-A", "morag_worker", "worker", "--loglevel=info", "--concurrency=2"]

  morag-worker-2:
    build:
      context: .
      target: production
    container_name: morag-worker-2
    restart: unless-stopped
    env_file: .env
    environment:
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
      # CPU Compatibility Settings
      - MORAG_FORCE_CPU=true
      - MORAG_DISABLE_DOCLING=false
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      # PyTorch CPU Compatibility
      - PYTORCH_DISABLE_NNPACK=1
      - PYTORCH_DISABLE_AVX=1
      - PYTORCH_DISABLE_AVX2=1
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./temp:/app/temp
    command: ["scripts/start_worker_safe.sh", "celery", "-A", "morag_worker", "worker", "--loglevel=info", "--concurrency=2"]

  # Celery Beat for scheduled tasks
  morag-beat:
    build:
      context: .
      target: production
    container_name: morag-beat
    restart: unless-stopped
    env_file: .env
    environment:
      - HF_HOME=/home/morag/.cache/huggingface
      - TRANSFORMERS_CACHE=/home/morag/.cache/huggingface
      - WHISPER_CACHE_DIR=/home/morag/.cache/whisper
      # CPU Compatibility Settings
      - MORAG_FORCE_CPU=true
      - MORAG_DISABLE_DOCLING=false
      - OMP_NUM_THREADS=1
      - MKL_NUM_THREADS=1
      - OPENBLAS_NUM_THREADS=1
      - VECLIB_MAXIMUM_THREADS=1
      - NUMEXPR_NUM_THREADS=1
      # PyTorch CPU Compatibility
      - PYTORCH_DISABLE_NNPACK=1
      - PYTORCH_DISABLE_AVX=1
      - PYTORCH_DISABLE_AVX2=1
    depends_on:
      - redis
      - mariadb
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    command: ["celery", "-A", "morag_worker", "beat", "--loglevel=info"]

volumes:
  redis_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  default:
    name: morag-network
    driver: bridge
