"""Data models for generation agents."""

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field
from enum import Enum


class ConfidenceLevelExamples:
    """Example confidence levels for reference only - NOT enforced.

    The system supports any domain-specific confidence levels generated by LLMs.
    These are provided as examples of common confidence categories.
    """
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"


class SummaryTypeExamples:
    """Example summary types for reference only - NOT enforced.

    The system supports any domain-specific summary types generated by LLMs.
    These are provided as examples of common summary types.
    """
    EXTRACTIVE = "extractive"
    ABSTRACTIVE = "abstractive"
    HYBRID = "hybrid"


class SummarizationResult(BaseModel):
    """Result from summarization."""

    summary: str = Field(..., description="Generated summary")
    key_points: List[str] = Field(..., description="Key points extracted")
    summary_type: str = Field(..., description="Type of summary (domain-specific, LLM-generated)")
    compression_ratio: float = Field(..., description="Compression ratio")
    confidence: str = Field(..., description="Confidence in summary (domain-specific, LLM-generated)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class ResponseGenerationResult(BaseModel):
    """Result from response generation."""

    response: str = Field(..., description="Generated response")
    response_type: str = Field(..., description="Type of response (domain-specific, LLM-generated)")
    sources: List[str] = Field(default_factory=list, description="Sources used")
    confidence: str = Field(..., description="Confidence in response (domain-specific, LLM-generated)")
    citations: List[Dict[str, Any]] = Field(default_factory=list, description="Citations")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class ExplanationResult(BaseModel):
    """Result from explanation generation."""

    explanation: str = Field(..., description="Generated explanation")
    explanation_type: str = Field(..., description="Type of explanation (domain-specific, LLM-generated)")
    reasoning_steps: List[str] = Field(..., description="Reasoning steps")
    examples: List[str] = Field(default_factory=list, description="Supporting examples")
    confidence: str = Field(..., description="Confidence in explanation (domain-specific, LLM-generated)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")


class SynthesisResult(BaseModel):
    """Result from synthesis."""

    synthesis: str = Field(..., description="Synthesized content")
    sources_integrated: int = Field(..., description="Number of sources integrated")
    coherence_score: float = Field(..., description="Coherence score")
    confidence: str = Field(..., description="Confidence in synthesis (domain-specific, LLM-generated)")
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Additional metadata")
