[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "morag-image"
version = "0.1.0"
description = "Image processing capabilities for MoRAG (Multimodal RAG Ingestion Pipeline)"
authors = [{name = "Your Name", email = "your.email@example.com"}]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    "morag-core>=0.1.0,<0.2.0",
    "Pillow>=10.0.0,<11.0.0",
    "pytesseract>=0.3.10,<0.4.0",
    "easyocr>=1.7.0,<2.0.0",
    "opencv-python>=4.8.0,<5.0.0",
    "google-generativeai>=0.3.0,<0.4.0",
    "structlog>=24.4.0,<25.0.0",
    "aiofiles>=23.2.1,<24.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0,<8.0.0",
    "pytest-asyncio>=0.21.0,<1.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
    "black>=23.0.0,<24.0.0",
    "isort>=5.12.0,<6.0.0",
    "flake8>=6.0.0,<7.0.0",
    "mypy>=1.7.0,<2.0.0",
]

[project.urls]
Homepage = "https://github.com/yourusername/morag"
Repository = "https://github.com/yourusername/morag"
Documentation = "https://github.com/yourusername/morag/docs"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.isort]
profile = "black"
multi_line_output = 3

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true