apiVersion: apps/v1
kind: Deployment
metadata:
  name: morag-api
  labels:
    app: morag-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: morag-api
  template:
    metadata:
      labels:
        app: morag-api
    spec:
      containers:
      - name: api
        image: morag:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_URL
          value: "redis://redis-service:6379/0"
        - name: QDRANT_HOST
          value: "qdrant-service"
        - name: GEMINI_API_KEY
          valueFrom:
            secretKeyRef:
              name: morag-secrets
              key: gemini-api-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: morag-uploads-pvc
      - name: logs
        persistentVolumeClaim:
          claimName: morag-logs-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: morag-api-service
spec:
  selector:
    app: morag-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: morag-uploads-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: morag-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: morag-secrets
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  gemini-api-key: eW91cl9nZW1pbmlfYXBpX2tleV9oZXJl  # your_gemini_api_key_here
