[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "morag-services"
version = "0.1.0"
description = "Service integration layer for MoRAG system"
authors = [
    {name = "MoRAG Team", email = "info@morag.ai"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]
dependencies = [
    "morag-core>=0.1.0",
    "morag-document>=0.1.0",
    "morag-audio>=0.1.0",
    "morag-video>=0.1.0",
    "morag-image>=0.1.0",
    "morag-embedding>=0.1.0",
    "morag-web>=0.1.0",
    "morag-youtube>=0.1.0",
    "structlog>=23.1.0",
    "pydantic>=2.0.0",
    "aiofiles>=23.1.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.3.1",
    "pytest-asyncio>=0.21.0",
    "black>=23.3.0",
    "isort>=5.12.0",
    "mypy>=1.3.0",
    "ruff>=0.0.270",
]

[project.urls]
"Homepage" = "https://github.com/morag-ai/morag"
"Bug Tracker" = "https://github.com/morag-ai/morag/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.black]
line-length = 88
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"
line_length = 88

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true